In [1]:
import numpy as np
import pandas as pd
import jieba
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.svm import SVC
from sklearn.externals import joblib

In [2]:
news = pd.read_csv('sqlResult_1558435.csv', encoding='gb18030')

In [3]:
news.dropna(inplace=True)

In [4]:
news.replace({'source': r'^(新华社)'},{'source': 1}, regex=True, inplace=True)

In [5]:
news.loc[news['source'] != 1, 'source'] = 2

In [6]:
news = news.reset_index()

In [7]:
news.head(300)

index     id       author  source  \
0        4  89613   胡淑丽_MN7479       2   
1        5  89612           张怡       2   
2        7  89610       申玉彬 整理       2   
3        8  89609   李杭_BJS4645       2   
4        9  89608           吴瞬       2   
5       13  89604       申玉彬 整理       2   
6       15  89602          费天元       2   
7       18  89599           张怡       2   
8       19  89598        周佳 整理       2   
9       21  89596        周佳 整理       2   
10      23  89594           张怡       2   
11      24  89593    屠震林 PS040       2   
12      54  89563   李天奕_NN7528       2   
13      59  89558     王璐 PS039       2   
14     112  89505           官平       2   
15     126  89491   荀建国_NN7379       2   
16     143  89474          张田宇       2   
17     145  89472          王志胜       2   
18     146  89471           查希       2   
19     147  89470    屠震林 PS040       2   
20     148  89469          张田宇       2   
21     149  89468          张田宇       2   
22     151  89466          陈晨1       2   
23     152  89465          张田宇       2   
24     154  89463          张田宇       2   
25     155  89462     徐俊 PS001       2   
26     158  89459          张田宇       2   
27     161  89456          张田宇       2   
28     165  89452           查希       2   
29     168  89449          张田宇       2   
..     ...    ...          ...     ...   
270    774  88843    高轶楠 PK078       2   
271    781  88836   柳聪_BJS3376       2   
272    784  88833           李芳       2   
273    785  88832    高轶楠 PK078       2   
274    787  88830          王炯业       2   
275    788  88829          李鸿涛       2   
276    791  88826           陈博       2   
277    793  88824   柳聪_BJS3376       2   
278    794  88823          卜晓明       1   
279    796  88821           李芳       2   
280    797  88820           老任       2   
281    799  88818           刘畅       2   
282    800  88817     于峥 PK072       2   
283    807  88810     于峥 PK072       2   
284    810  88807          张启畅       1   
285    811  88806           李芳       2   
286    815  88802           李芳       2   
287    816  88801          张雪飞       1   
288    819  88798  张宪超_BJS2970       2   
289    820  88797           朱晟       2   
290    821  88796           李芳       2   
291    823  88794           陈博       2   
292    826  88791         阿思达克       2   
293    828  88789    隋奕菲 PK036       2   
294    831  88786           李芳       2   
295    832  88785          王宙洁       2   
296    834  88783   柳聪_BJS3376       2   
297    839  88778   柳聪_BJS3376       2   
298    841  88776          王清妍       2   
299    843  88774   荀建国_NN7379       2   

                                               content  \
0    （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\r\n@深圳交警微博称：昨日清...   
1    　　受到A股被纳入MSCI指数的利好消息刺激，A股市场从周三开始再度上演龙马行情，周四上午金...   
2    　　沙漠雄鹰：震荡有利消化套牢筹码\r\n　　周四开盘上证50在银行券商大蓝筹带动下一度涨近...   
3    （原标题：武汉警方一下子抓了808人，还都是俊男靓女！原来他们每天偷偷摸摸干这事！）\r\n...   
4    　　6月21日，A股纳入MSCI指数尘埃落定，但当天被寄予厚望的券商股并未扛起反弹大旗。22...   
5    　　曹先生：风格转换前的阵痛\r\n　　今日早盘两地低开，之后一度震荡走高，领涨的仍然是上证...   
6    　　中国证券网讯（记者 费天元）沪深两市周五临近午盘出现快速跳水，沪指连续跌穿5日、10日及...   
7    　　中证网讯 （本报记者 张怡）今日，三板做市指数继续低开下行，盘中最低触及1057.91点...   
8    　　提示声明：\r\n　　本文涉及的行业及个股分析来源于券商研究报告，仅为分析人士对该行业及...   
9    　　提示声明：\r\n　　本文涉及的行业及个股分析来源于券商研究报告，仅为分析人士对该行业及...   
10   　　中证网讯 （本报记者 张怡）与此前两日蓝筹股强势格局不同，周五，A股市场主要指数低开之后...   
11   北京时间6月20日，江苏苏宁足球俱乐部发布了足协杯第四轮江苏苏宁易购队主场对阵河南建业队的官...   
12   （原标题：高速上50秒别车6次 面包车司机现身：我一时冲动犯了错）\r\n高速上50秒别车6...   
13   中超将告别天价外援\r\n6月20日下午，中国足协下发了《关于2017夏季注册转会期收取引援...   
14   　　证监会副主席方星海近日表示，如果不是停牌，原本能有更多A股股票纳入摩根士丹利资本国际公司...   
15   （原标题：伊朗和俄罗斯向卡塔尔提出援助 卡塔尔：暂时还不需要）\r\n【环球网综合报道】据俄...   
16   　　由湖南卫视携手盛唐时空制作、南派三叔担任总编剧的原创文化探秘节目《七十二层奇楼》已于上周...   
17   　　北京协和医院内分泌科垂体性腺组和京医会联合举办的第二届北京协和下丘脑-垂体-性腺疾病高峰...   
18   　　【环球网报道 实习记者 田瑞哲】当地时间18日晚，一辆货车在英国伦敦芬斯伯里公园附近的七...   
19   凤凰体育讯北京时间6月16日，江苏苏宁足球俱乐部发布了中超联赛第13轮江苏苏宁易购队主场对阵...   
20   　　由北京卫视重磅推出，北京电视台、华录百纳蓝火、完美世界影视、鑫宝源、北京文化、京视卫星传...   
21   　　由江苏卫视重磅推出的全新锻造式综艺《来吧，兄弟》正在热拍中，陈小春、包贝尔、潘玮柏、孙坚...   
22   　　【环球网综合报道】露脚踝是众所周知的显瘦妙招。然而，只有搭配了合适的鞋子才能让脚踝显得更...   
23   　　东

In [8]:
with open('./stop_words.utf8') as f: 
    stop_words =  [l.strip() for l in f]

In [9]:
def cut(string): return [word for word in list(jieba.cut(string)) if word not in stop_words]

In [10]:
all_contents = news['content']

In [11]:
all_contents = [' '.join(cut(s)) for s in all_contents]

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/_8/f14fxxnn7w13cd0l5x9hl4bm0000gn/T/jieba.cache
Loading model cost 0.847 seconds.
Prefix dict has been built succesfully.


In [12]:
all_contents[0]

'原 标题 44 岁 女子 跑 深圳 约会 网友 拒 暴雨 中 裸身 奔走 \r\n 深圳 交警 微博称 昨日 清晨 交警 发现 女子 赤裸 上身 行走 南坪 快速 期间 轻生 年头 一辅警 发现 赶紧 披上 黄衣 一路 劝说 \r\n 事发 时 \r\n 到底 发生 \r\n 南 记者 带 一起 还原 现场 \r\n 南 记者 龙岗 大队 坂田 中队 见到 辅警 刘青 发现 女生 辅警 一位 外表 高大 帅气 说话 略带 腼腆 90 青年 \r\n 刘青 介绍 月 16 日 早上 时 36 分 正在 环城 南路 附近 值勤 接到 中队 一位 女子 裸身 进入 机动车 可能 危险 警情 骑着 铁骑 沿路 寻找 大概 花 十多分钟 南坪 大道 坂田 出口 龙岗 方向 逆行 辅道 发现 女子 \r\n 女子 身上 一丝不挂 地逆 车流 而行 时 走时 停 时 坐 时 躺 险象环生 刘青停 铁骑 一名 巡防 员 追 上去 发现 女子 情绪 低落 话 刘青 尝试 女子 交流 劝说 女子 离开 女子 愿意 接受 继续 缓慢 地往 南坪 快速路 主干道 走 \r\n 路边 已经 聚集 市民 围观 刺激 女子 情绪 刘青 巡防 员 一边 盯 女子 一边 驱赶 围观 群众 \r\n 现场 还原 \r\n 警方 提供 一份 视频 了解 16 日 早上 时 25 分 女子 出现 坂雪岗 大道 环城 南路 监控 视频 中 女子 穿着 白色 内裤 正 坂雪岗 大道 南坪 快速 方向 缓慢 走 \r\n 当时 上班 高峰期 十字路口 车流 已经 排起 长队 女子 出现 时 路上 市民 纷纷 驻足 观望 不少 车辆 放慢 速度 女子 市民 观望 停下 脚步 依然 缓慢 走 女子 行进 十字路口 中间 时 一辆 货车 挡住 镜头 女子 再次出现 镜头 时 发现 女子 已经 没 穿 内裤 全身 裸露 继续 南坪 快速 方向 走 记者 发现 视频 中 女子 周围 没有 尾随 上前 劝止 市民 \r\n 大清早 路上 看到 情况 \r\n 恐怕 没 办法 淡定 \r\n 面对 这一 情况 \r\n 刘青 表示 根本 不敢 心里 挺 别扭 感觉 尴尬 刘青 跟随 女子 南坪 快速路 主干道 时 女子 作出 意想不到 举动 突然 靠近 护栏 上面 跳下去 刘青 赶忙 冲上去 拉住 女子 手 控制 住 远离

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [14]:
vectorizer = TfidfVectorizer(max_features=3000)

In [15]:
X = vectorizer.fit_transform(all_contents)

In [16]:
X.shape

(76925, 3000)

In [17]:
y = pd.to_numeric(news['source']).values

In [18]:
y

array([2, 2, 2, ..., 1, 1, 1])

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [20]:
clf = SVC(random_state=0)

In [21]:
param_grid = [{'C': [i for i in range(1, 3)]}]

In [22]:
grid_search = GridSearchCV(clf, param_grid, n_jobs=-1, verbose=3, scoring='accuracy')

In [23]:
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 2 candidates, totalling 6 fits


/anaconda3/envs/Kstone/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   6 | elapsed:  2.7min remaining:  5.5min
[Parallel(n_jobs=-1)]: Done   6 out of   6 | elapsed:  4.7min finished
/anaconda3/envs/Kstone/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=-1, param_grid=[{'C': [1, 2]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=3)

In [24]:
scores = cross_val_score(grid_search.best_estimator_, X_train, y_train, cv=3, scoring='accuracy')
print(scores.mean(), scores)

/anaconda3/envs/Kstone/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9685033530596469 [0.96846797 0.96852192 0.96852017]


In [26]:
scores = cross_val_score(grid_search.best_estimator_, X_test, y_test, cv=3, scoring='accuracy')
print(scores.mean(), scores)

/anaconda3/envs/Kstone/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9693214315513129 [0.96932276 0.96932276 0.96931877]


In [27]:
joblib.dump(grid_search.best_estimator_, './model-svc.pkl')

['./model-svc.pkl']

In [29]:
svc = grid_search.best_estimator_

In [31]:
svc.predict(X_test)

array([1, 1, 1, ..., 1, 1, 1])

In [38]:
np.where(svc.support_vectors_.toarray())[0]

array([   0,    0,    0, ..., 3420, 3420, 3420])