## N-dimensional Arrays

In [1]:
import numpy as np

In [2]:
lst = [[1, 2, 3], [4, 5, 6]]

In [3]:
ary1d = np.array(lst)

In [4]:
ary1d

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(ary1d)

numpy.ndarray

In [6]:
ary1d.dtype

dtype('int64')

In [7]:
float32_ary = ary1d.astype(np.float32)

In [8]:
float32_ary

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

### 左边有几个中括号，就有几个维度

In [9]:
ary2d = np.array([[1, 2, 3], [4, 5, 6]], dtype='int64')

In [10]:
ary2d.itemsize

8

In [11]:
ary2d.size

6

In [12]:
ary2d.ndim

2

In [14]:
ary2d.shape

(2, 3)

In [13]:
three_np = np.array([1, 2, 3])

In [14]:
three_np

array([1, 2, 3])

In [15]:
three_np.shape

(3,)

In [16]:
three_np.ndim

1

In [16]:
scalar = np.array(5)

In [17]:
scalar

array(5)

In [18]:
scalar.ndim

0

In [19]:
scalar.shape

()

## Array Construction Routines

In [33]:
def generator():
    for i in range(10):
        if i % 2:
            yield i

In [34]:
gen = generator()

In [35]:
type(gen)

generator

In [36]:
np.fromiter(gen, dtype=int)

array([1, 3, 5, 7, 9])

In [42]:
generator_expression = (i for i in range(10) if i % 2)

In [43]:
fromiter_np = np.fromiter(generator_expression, dtype=int)

In [44]:
fromiter_np.shape

(5,)

In [45]:
fromiter_np

array([1, 3, 5, 7, 9])

In [41]:
np.ones((3, 3, 4, 5))

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1.,

In [25]:
one_np = np.ones((1, 2))

In [31]:
one_np

array([[1., 1.]])

In [26]:
one_np.shape

(1, 2)

In [ ]:
np.zeros((3, 3))

In [46]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye

In [50]:
np.diag((3, 4, 5, 6))

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [48]:
np.arange(4., 10.)

array([4., 5., 6., 7., 8., 9.])

In [49]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(1., 11., 2)

array([1., 3., 5., 7., 9.])

In [51]:
np.linspace(0., 1., num=4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [58]:
np.linspace(100, 101, num=3)

array([100. , 100.5, 101. ])

## Array Indexing

In [59]:
ary = np.array([1, 2, 3])

In [60]:
ary[0]

1

In [61]:
ary[:2]

array([1, 2])

In [62]:
ary = np.array([[1, 2, 3], [4, 5, 6]])

In [63]:
ary[0, 0]

1

In [64]:
ary[-1, -1]

6

In [65]:
ary[0, 1]

2

In [66]:
ary[0]

array([1, 2, 3])

In [67]:
ary[:, 0]

array([1, 4])

In [68]:
ary[:, :2]

array([[1, 2],
       [4, 5]])

In [69]:
ary[0, 0]

1