In [1]:
from keras import Input, layers

In [2]:
input_tensor = Input(shape=(32, ))

In [3]:
dense = layers.Dense(32, activation='relu')

In [4]:
output_tensor = dense(input_tensor)

In [6]:
output_tensor.shape

TensorShape([Dimension(None), Dimension(32)])

In [7]:
from keras.models import Sequential, Model
from keras import layers
from keras import Input

In [8]:
seq_model = Sequential()

In [9]:
seq_model.add(layers.Dense(32, activation='relu', input_shape=(64,)))
seq_model.add(layers.Dense(32, activation='relu'))
seq_model.add(layers.Dense(10, activation='softmax'))

In [10]:
input_tensor = Input(shape=(64,))
x = layers.Dense(32, activation='relu')(input_tensor)
x = layers.Dense(32, activation='relu')(x)
output_tensor = layers.Dense(10, activation='softmax')(x)

In [11]:
model = Model(input_tensor, output_tensor)

In [12]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 64)                0         
_________________________________________________________________
dense_5 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_6 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_7 (Dense)              (None, 10)                330       
Total params: 3,466
Trainable params: 3,466
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(optimizer='rmsprop', loss='categorical_crossentropy')

In [14]:
import numpy as np

In [15]:
x_train = np.random.random((1000, 64))
y_train = np.random.random((1000, 10))

In [16]:
model.fit(x_train, y_train, epochs=10, batch_size=128)

Epoch 1/10
1000/1000 [==============================] - 0s 239us/step - loss: 11.6010
Epoch 2/10
1000/1000 [==============================] - 0s 28us/step - loss: 11.5295
Epoch 3/10
1000/1000 [==============================] - 0s 31us/step - loss: 11.5174
Epoch 4/10
1000/1000 [==============================] - 0s 30us/step - loss: 11.5091
Epoch 5/10
1000/1000 [==============================] - 0s 18us/step - loss: 11.5028
Epoch 6/10
1000/1000 [==============================] - 0s 22us/step - loss: 11.4985
Epoch 7/10
1000/1000 [==============================] - 0s 29us/step - loss: 11.4951
Epoch 8/10
1000/1000 [==============================] - 0s 26us/step - loss: 11.4916
Epoch 9/10
1000/1000 [==============================] - 0s 18us/step - loss: 11.4889
Epoch 10/10
1000/1000 [==============================] - 0s 22us/step - loss: 11.4862


In [17]:
score = model.evaluate(x_train, y_train)

1000/1000 [==============================] - 0s 51us/step


In [1]:
from keras.models import Model
from keras import layers
from keras import Input

Using TensorFlow backend.


In [2]:
text_vocabulary_size = 10000
question_vocabulary_size = 10000
answer_vocabulary_size = 500

In [3]:
text_input = Input(shape=(None,), dtype='int32', name='text')

In [4]:
embedded_text = layers.Embedding(text_vocabulary_size, 64)(text_input)

In [5]:
encoded_text = layers.LSTM(32)(embedded_text)

In [6]:
question_input = Input(shape=(None,), dtype='int32', name='question')

In [7]:
embedded_question = layers.Embedding(question_vocabulary_size, 32)(question_input)

In [8]:
encoded_question = layers.LSTM(16)(embedded_question)

In [9]:
concatenated = layers.concatenate([encoded_text, encoded_question], axis=-1)

In [10]:
answer = layers.Dense(answer_vocabulary_size, activation='softmax')(concatenated)

In [11]:
model = Model([text_input, question_input], answer)

In [12]:
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['acc'])

In [13]:
import numpy as np

In [14]:
num_samples = 1000
max_length = 100

In [15]:
text = np.random.randint(1, text_vocabulary_size, size=(num_samples, max_length))

In [16]:
text.shape

(1000, 100)

In [17]:
question = np.random.randint(1, question_vocabulary_size, size=(num_samples, max_length))

In [18]:
question.shape

(1000, 100)

In [19]:
answers = np.random.randint(answer_vocabulary_size, size=(num_samples))

In [33]:
answers

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [26]:
answers.shape

(1000, 500)

In [21]:
import keras

In [22]:
answers = keras.utils.to_categorical(answers, answer_vocabulary_size)

In [46]:
model.fit([text, question], answers, epochs=10, batch_size=128)

Epoch 1/10
1000/1000 [==============================] - 3s 3ms/step - loss: 6.2142 - acc: 1.0000e-03
Epoch 2/10
1000/1000 [==============================] - 1s 1ms/step - loss: 6.1972 - acc: 0.0310
Epoch 3/10
1000/1000 [==============================] - 1s 1ms/step - loss: 6.1284 - acc: 0.0060
Epoch 4/10
1000/1000 [==============================] - 1s 1ms/step - loss: 6.0444 - acc: 0.0050
Epoch 5/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.9928 - acc: 0.0040
Epoch 6/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.9391 - acc: 0.0080
Epoch 7/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.8728 - acc: 0.0080
Epoch 8/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.8035 - acc: 0.0100
Epoch 9/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.7206 - acc: 0.0120
Epoch 10/10
1000/1000 [==============================] - 1s 1ms/step - loss: 5.6450 - acc: 0.0120


In [47]:
from keras import layers
from keras import Input
from keras.models import Model

In [48]:
vocabulary_size = 50000
num_incom_groups = 10

In [49]:
posts_input = Input(shape=(None,), dtype='int32', name='posts')

In [51]:
embeded_posts = layers.Embedding(256, vocabulary_size)(posts_input)

In [52]:
x = layers.Conv1D(128, 5, activation='relu')(embeded_posts)

In [53]:
x = layers.MaxPooling1D(5)(x)

In [54]:
x = layers.Conv1D(256, 5, activation='relu')(x)

In [55]:
x = layers.Conv1D(256, 5, activation='relu')(x)

In [56]:
x = layers.MaxPooling1D(5)(x)

In [57]:
x = layers.Conv1D(256, 5, activation='relu')(x)

In [58]:
x = layers.Conv1D(256, 5, activation='relu')(x)

In [59]:
x = layers.GlobalMaxPooling1D()(x)

In [60]:
x = layers.Dense(128, activation='relu')(x)

In [61]:
age_prediction = layers.Dense(1, name='age')(x)

In [62]:
income_prediction = layers.Dense(num_incom_groups, activation='softmax', name='income')(x)

In [63]:
gender_prediction = layers.Dense(1, activation='sigmoid', name='gender')(x)

In [64]:
model = Model(posts_input, [age_prediction, income_prediction, gender_prediction])

In [65]:
model.compile(optimizer='rmsprop', loss=['mse', 'categorical_crossentropy', 'binary_crossentropy'], 
              loss_weights=[0.25, 1., 10.])

In [ ]:
model.fit(posts, [age_targets, income_targets, gender_targets], epochs=10, batch_size=64)

In [31]:
temp = np.random.randint(4, size=(4))

In [32]:
temp

array([3, 2, 3, 1])

In [34]:
answers = keras.utils.to_categorical(temp, 4)

In [35]:
answers

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.]], dtype=float32)

In [36]:
tem = keras.utils.to_categorical([1, 0, -1, -2], 4)

In [37]:
tem

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)